import fs from 'fs';
import path from 'path';
import { ASSETS, MANIFEST_JSON, MANIFEST_JS, OVERRIDES_JSON, ROOT, relAsset, ensureDir } from './paths.js';
import { loadCities } from './load-cities.js';
import { landmarkSlug } from './slug.js';
import {
  cityHeroFallbackPath,
  cityThumbFallbackPath,
  landmarkFallbackPath,
  writeCityFallbacks,
  writeLandmarkFallback,
} from './fallback.js';
import { loadCache } from './cache.js';

function fileIfExists(p) {
  return fs.existsSync(p) ? relAsset(p) : null;
}

function loadOverrides() {
  if (!fs.existsSync(OVERRIDES_JSON)) return { cities: {}, landmarks: {} };
  try {
    return JSON.parse(fs.readFileSync(OVERRIDES_JSON, 'utf8'));
  } catch {
    return { cities: {}, landmarks: {} };
  }
}

export function buildManifest() {
  const cities = loadCities();
  const overrides = loadOverrides();
  const cache = loadCache();

  const manifest = {
    version: 1,
    generatedAt: new Date().toISOString(),
    cities: {},
    landmarks: {},
  };

  for (const c of cities) {
    const heroJpg = path.join(ASSETS, 'cities', c.id, 'hero.jpg');
    const thumbJpg = path.join(ASSETS, 'cities', c.id, 'thumb.jpg');
    const heroSvg = cityHeroFallbackPath(c.id);
    const thumbSvg = cityThumbFallbackPath(c.id);

    const heroImage =
      overrides.cities?.[c.id]?.heroImage ||
      fileIfExists(heroJpg) ||
      fileIfExists(heroSvg);
    const heroThumb =
      overrides.cities?.[c.id]?.heroThumb ||
      fileIfExists(thumbJpg) ||
      fileIfExists(thumbSvg) ||
      heroImage;

    const cached = cache.heroes[c.id];
    manifest.cities[c.id] = {
      heroImage,
      heroThumb,
      source: cached?.source || (fileIfExists(heroJpg) ? 'fetched' : 'fallback'),
      fallback: !fileIfExists(heroJpg),
      ...(cached?.query ? { query: cached.query } : {}),
      ...(cached?.title ? { title: cached.title } : {}),
    };

    for (const l of c.landmarks || []) {
      const slug = l.slug || landmarkSlug(c.id, l.name);
      const key = `${c.id}/${slug}`;
      const lmJpg = path.join(ASSETS, 'landmarks', c.id, `${slug}.jpg`);
      const lmSvg = landmarkFallbackPath(c.id, slug);

      const image =
        overrides.landmarks?.[key]?.image ||
        overrides.landmarks?.[slug]?.image ||
        fileIfExists(lmJpg) ||
        fileIfExists(lmSvg);

      const lc = cache.landmarks[key] || cache.landmarks[slug];
      manifest.landmarks[key] = {
        name: l.name,
        image,
        source: lc?.source || (fileIfExists(lmJpg) ? 'fetched' : 'fallback'),
        fallback: !fileIfExists(lmJpg),
        ...(lc?.query ? { query: lc.query } : {}),
      };
    }
  }

  ensureDir(path.dirname(MANIFEST_JSON));
  fs.writeFileSync(MANIFEST_JSON, JSON.stringify(manifest, null, 2));

  const js = `// Auto-generated by scripts/image-pipeline — do not edit by hand\n// Re-run: npm run manifest (in scripts/image-pipeline)\nwindow.TERRA_IMAGE_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`;
  fs.writeFileSync(MANIFEST_JS, js);

  return manifest;
}

export function generateAllFallbacks(cities) {
  for (const c of cities) {
    writeCityFallbacks(c);
    for (const l of c.landmarks || []) {
      writeLandmarkFallback(c, l);
    }
  }
}
